# Generated by Django 6.1 on 2026-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitabug',
            name='title',
            field=models.CharField(help_text='A short blurb about the bug you found', max_length=200, unique=True),
        ),
    ]
