# Generated by Django 6.1 on 2026-09-21 07:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_submitabug_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitABug',
            new_name='BugReport',
        ),
    ]
