# Generated by Django 6.1 on 2026-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_submitabug_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes on what is causing the bug/solutions after fixing', null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='related_bugs',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_bugs', to='core.bugreport'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='severity',
            field=models.CharField(choices=[('C', 'Critical'), ('M', 'Major'), ('T', 'Minor'), ('D', 'Unreviewed')], default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('R', 'Needs Reviwed'), ('P', 'In Progress'), ('F', 'Bug Fixed')], default='R', max_length=2),
        ),
    ]
