# Generated by Django 6.1 on 2026-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bugreport_notes_bugreport_related_bugs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='related_bugs',
            field=models.ManyToManyField(blank=True, to='core.bugreport'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('R', 'Needs Review'), ('P', 'In Progress'), ('F', 'Bug Fixed')], default='R', max_length=2),
        ),
    ]
