# Generated by Django 6.1 on 2026-09-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200)),
                ('swahili_def', models.CharField(max_length=500)),
                ('sentence', models.CharField(max_length=500)),
                ('part_of_speech', models.CharField(max_length=200)),
                ('verb_construction', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(verbose_name='Date Added')),
                ('date_modified', models.CharField(max_length=200)),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_added', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
