# Generated by Django 6.1 on 2026-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='swahili_def',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='verb_construction',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='construction',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='swahili_definition',
            field=models.CharField(blank=True, default='No Definition Listed', max_length=500),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='swahili_entry',
            field=models.CharField(default='NO ENTRY', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='date_modified',
            field=models.DateTimeField(verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='part_of_speech',
            field=models.CharField(blank=True, default='None Listed', max_length=200),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='sentence',
            field=models.CharField(blank=True, default='No Examples Listed', max_length=500),
        ),
    ]
