# Generated by Django 6.1 on 2026-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_dictionaryentry_swahili_def_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='translation_source',
            field=models.CharField(choices=[('G', 'GoogleTranslateAPI'), ('F', 'FreeDictionaryAPI'), ('U', 'UserAdded'), ('D', 'No Source Found')], default='D', max_length=2),
        ),
    ]
