# Generated by Django 6.1 on 2026-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_dictionaryentry_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='swahili_entry',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='translation_source',
            field=models.CharField(choices=[('G', 'GoogleTranslateAPI'), ('F', 'FreeDictionaryAPI'), ('U', 'UserAdded')], default='U', max_length=2),
        ),
    ]
