# Generated by Django 6.1 on 2026-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_dictionaryentry_swahili_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='translation_source',
            field=models.CharField(default='UserAdded', max_length=200),
        ),
    ]
