# Generated by Django 6.1 on 2026-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_dictionaryentry_translation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='construction',
            field=models.TextField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='sentence',
            field=models.TextField(blank=True, default='No Examples Listed'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='swahili_definition',
            field=models.TextField(blank=True, default='No Definition Listed'),
        ),
    ]
