# Generated by Django 6.1 on 2026-09-12 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_dictionaryentry_construction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='construction',
            field=models.TextField(blank=True, default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='user_added',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='user_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
