# Generated by Django 6.1 on 2026-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_alter_dictionaryentry_construction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='translation_source',
            field=models.CharField(default='User Added', max_length=200),
        ),
    ]
