# Generated by Django 6.1 on 2026-09-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_alter_dictionaryentry_translation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
