# Generated by Django 6.1 on 2026-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_alter_dictionaryentry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
