# Generated by Django 6.1 on 2026-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(default='No source found', max_length=500),
        ),
    ]
