# Generated by Django 6.1 on 2026-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_alter_content_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
