# Generated by Django 6.1 on 2026-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(default='No source found', help_text='Where is this content from? (URL, etc.)', max_length=500),
        ),
    ]
