# Generated by Django 6.1 on 2026-09-26 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_alter_content_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='site_content.content')),
                ('body', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('last_edit', models.DateTimeField(verbose_name='Last Modified')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_edited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
