# Generated by Django 6.1 on 2026-09-26 12:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
