# Generated by Django 6.1 on 2026-10-01 13:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_alter_lesson_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Lesson'),
        ),
    ]
