# Generated by Django 6.1 on 2026-09-16 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0008_alter_dictionaryentry_translation_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL, unique=True)),
                ('vocab_words', models.ManyToManyField(related_name='words', through='vocabulary.ListAddition', to='dictionary.dictionaryentry')),
            ],
        ),
        migrations.AddField(
            model_name='listaddition',
            name='vocab_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularylist'),
        ),
    ]
