# Generated by Django 6.1 on 2026-09-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_vocabularylist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaddition',
            name='added_from',
            field=models.CharField(blank=True, default='Added from Dictionary', max_length=200),
        ),
    ]
