# Generated by Django 6.1 on 2026-09-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_alter_content_source'),
        ('vocabulary', '0003_listaddition_added_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaddition',
            name='added_from',
        ),
        migrations.AddField(
            model_name='listaddition',
            name='added',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_content.content'),
        ),
    ]
