# Generated by Django 6.1 on 2026-09-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_remove_listaddition_added_from_listaddition_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaddition',
            old_name='added',
            new_name='added_from',
        ),
    ]
